name: 'supply_chain_warehouse'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: supply_chain_warehouse

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  supply_chain_warehouse:
    # The staging layer cleans and renames raw data. It should be materialized as views.
    staging:
      +materialized: view
    # The intermediate layer handles complex joins and business logic. 
    intermediate:
      +materialized: view
    # The marts layer is the final reporting layer. It should be materialized as tables for performance.
    marts:
      +materialized: table